### ISSUE TITLE
ask for a function

### ISSUE THREAD

**Issue by xuansuyang** [samirelanduk/pygtop#2]
I want to extract the ligand and receptor general comments and immune comments separately, is there a function to achieve this function?
thank you

**Comment by samirelanduk** [comment]
Hi, unfortunately I do not maintain this library any more as I have left the GtoP team, but @simondharding may be able to help with general API queries.

**Comment by simondharding** [comment]
Hi @xuansuyang - thanks for your enquiry. As Sam says, the repository doesn't currently have developer time to keep it maintained. I will have a look if I get an opportunity - apologies for any inconvenience.

**Comment by xuansuyang** [comment]
thanks for your answer. I have written code by your package to solve this question.
